version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://back:8001
    depends_on:
      - back
    networks:
      - app-network
    restart: unless-stopped

  back:
    build:
      context: ./runtime
      dockerfile: Dockerfile
    networks:
      - app-network
    env_file:
      - ./.env
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
