apiVersion: apps/v1
kind: Deployment
metadata:
  name: runtime-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runtime
  template:
    metadata:
      labels:
        app: runtime
    spec:
      containers:
      - name: runtime
        image: cr.yandex/crpfobr25c755gi1uh6f/myapp-runtime:init
        ports:
        - containerPort: 8001
        env:
          - name: YA_CATALOG_ID
            valueFrom:
              secretKeyRef:
                name: yagpt-secret
                key: catalog_id
          - name: YA_API_KEY
            valueFrom:
              secretKeyRef:
                name: yagpt-secret
                key: api_key

---

apiVersion: v1
kind: Service
metadata:
  name: runtime-service
spec:
  selector:
    app: runtime
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
