apiVersion: apps/v1
kind: Deployment
metadata:
  name: runtime-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runtime
  template:
    metadata:
      labels:
        app: runtime
    spec:
      containers:
      - name: runtime
        image: myapp-runtime
        ports:
        - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: runtime-service
spec:
  selector:
    app: runtime
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
