apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: cr.yandex/crpfobr25c755gi1uh6f/myapp-front:init
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
