apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: myapp
  labels:
    app: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      imagePullSecrets:
      - name: yc-registry-secret
      containers:
      - name: telegram-bot
        image: cr.yandex/crpfobr25c755gi1uh6f/telegram-bot:latest
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secrets
              key: BOT_TOKEN
        - name: ALLOWED_USERS
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secrets
              key: ALLOWED_USERS
        - name: BACKEND_URL
          value: "http://myapp-backend-service.myapp.svc.cluster.local:8001/generate"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
